# Generated by Django 4.1.2 on 2022-11-01 14:10

import StudyingProcess.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StudyingProcess', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studygroup',
            name='amount',
        ),
        migrations.AlterField(
            model_name='student',
            name='studygroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudyingProcess.studygroup', validators=[StudyingProcess.models.restrict_amount]),
        ),
    ]
