# Generated by Django 4.1.2 on 2022-11-03 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StudyingProcess', '0003_alter_curator_options_alter_curator_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curator',
            name='direction',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='StudyingProcess.direction'),
        ),
        migrations.AlterField(
            model_name='curator',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
