# Generated by Django 4.1.2 on 2022-11-03 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StudyingProcess', '0004_alter_curator_direction_alter_curator_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curator',
            name='direction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='StudyingProcess.direction'),
        ),
        migrations.AlterField(
            model_name='curator',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
