# Generated by Django 4.1.2 on 2022-11-03 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudyingProcess', '0009_alter_curator_direction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Male'), (2, 'Female')], null=True, verbose_name='Gender'),
        ),
    ]
