# Generated by Django 4.1.2 on 2022-11-04 15:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudyingProcess', '0017_alter_curator_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(default=79291658524, max_length=16, unique=True, validators=[django.core.validators.RegexValidator(regex='^7?1?\\d{10,10}$')]),
            preserve_default=False,
        ),
    ]
